### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dbdikcn** [924973292/EDITOR#3]
Congratulations on getting your paper published. May I ask under which path the pre-training Vit-B is placed

**Comment by dbdikcn** [comment]
已解决

**Comment by 924973292** [comment]
Thanks for your attention!
Here is the path:
<img width="593" alt="截屏2024-03-29 07 28 12" src="https://github.com/924973292/EDITOR/assets/89966785/9eea48fd-0a12-404b-8b7e-e1220d9bf31d">
You should place it to "your/path/to/pretrain...", where you can find in the config files!
If you have any questions,  just ask me!
