### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'shape'

### ISSUE THREAD

**Issue by dbdikcn** [924973292/EDITOR#4]
Traceback (most recent call last):
  File "/home/tiancun/EDITOR/modeling/backbones/vit_pytorch.py", line 666, in load_param
    self.state_dict()[k].copy_(v)
KeyError: 'state_dict_ema'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tiancun/EDITOR/train_net.py", line 71, in <module>
    model = make_model(cfg, num_class=num_classes, camera_num=camera_num)
  File "/home/tiancun/EDITOR/modeling/make_model.py", line 372, in make_model
    model = EDITOR(num_class, cfg, camera_num, __factory_T_type)
  File "/home/tiancun/EDITOR/modeling/make_model.py", line 89, in __init__
    self.BACKBONE = build_transformer(num_classes, cfg, camera_num, factory)
  File "/home/tiancun/EDITOR/modeling/make_model.py", line 63, in __init__
    self.base.load_param(model_path)
  File "/home/tiancun/EDITOR/modeling/backbones/vit_pytorch.py", line 669, in load_param
    print('shape do not match in k :{}: param_dict{} vs self.state_dict(){}'.format(k, v.shape,
AttributeError: 'dict' object has no attribute 'shape'

Sorry to bother you. When I was training RGBNT201, I used pre-training 82.6_T2T_ViTt_24_pth and this error occurred. How did you solve it?

**Comment by 924973292** [comment]
Feel free to ask!
<img width="452" alt="截屏2024-03-30 11 11 35" src="https://github.com/924973292/EDITOR/assets/89966785/3f2ce2e2-645a-4273-8fd5-a271970107e9">
The 'load param' code in the backbone is identical to that used in TOP-ReID. In TOP-ReID, I didn't make any adjustments when loading the parameters. You should set the checkpoint here and verify whether the param_dict has been loaded correctly.

**Comment by dbdikcn** [comment]
I'm sorry to bother you. I have confirmed that the param_dict failed to load successfully. But there is no solution yet.

**Comment by 924973292** [comment]
That's all right, check my personal website, and you can find my QQ or WeChat, we can communicate easily!

**Comment by dbdikcn** [comment]
Well. I add your qq

**Comment by ChenCherry** [comment]
你好 我也遇到相同问题 请问怎么解决的
