### ISSUE TITLE
Market1501不可以直接训练吗？

### ISSUE THREAD

**Issue by starsky68** [924973292/EDITOR#5]
Market1501不可以直接训练吗？必须转为Market1501MM ?

**Comment by 924973292** [comment]
Market1501 can be directly trained, but it might lack a reasonable motivation.

1. EDITOR is specifically designed for multi-modal inputs, which involves modality-cooperative selection and subsequent multi-modal feature fusion.

2. Market1501 is a single-modal input dataset, whereas Market1501-MM includes RGB, grayscale, and generated infrared images. Therefore, Market1501-MM can be directly used for testing.

3. Market1501 can be run by duplicating the input three times, but this approach lacks a reasonable motivation and significance. Unless you're trying to utilize multi-view strategies, where an image might have different augmentation strategies, this can be used to run EDITOR. Alternatively, you could split the RGB channels into three separate images to simulate a tri-modal input.
