### ISSUE TITLE
模型预训练权重问题

### ISSUE THREAD

**Issue by Elite35P** [924973292/EDITOR#8]
请问可否分享除ViT-B之外其他模块的预训练权重

**Comment by 924973292** [comment]
Apologies for the delay; I've been tied up with other work recently. Please check the link below for the model weights and training files that I reran today:

- [x] https://pan.baidu.com/s/12niOJxukD7cStH3R_Y9hBQ 
- [x] j2r3 

Python Version: 3.10.13
CUDA Version: 12.2

**Comment by Elite35P** [comment]
Thank you for the update and for sharing the weights for RGBNT201. I appreciate your efforts despite your busy schedule.  

---- 回复的原邮件 ----
| 发件人 | Yuhao ***@***.***> |
| 发送日期 | 2024年10月24日 14:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [924973292/EDITOR] 模型预训练权重问题 (Issue #8) |

Apologies for the delay. I've been busy with other work recently. I'm rerunning the code and will release the weights. Here is the weight for the small dataset RGBNT201:

https://pan.baidu.com/s/1RPggEmOPmXUXGbAJCCCFUQ
lvwf

Python Version: 3.10.13
CUDA Version: 12.2
